[package]
name = "jan-19"
version = "0.1.0"
authors = ["lineville <lneville@quantumscape.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
